title: Tarun's Website
author: Tarun Sivakumar
email: tsivakumar@ebnet.org
description: CSP Final Project
instagram_username: tarun.sivakumar
github_username:  Tarun-Sivakumar

show_excerpts: true # set to false to remove excerpts on the homepage
